Claude Google Bot Preflight trigger.

requested_at=2026-08-26T22:39:30Z
requested_by=gpt
reason=validate_new_solana_rpc_runtime_configuration_after_operator_change
validation_scope=non_trading_preflight_only
privacy=do_not_print_rpc_urls_or_api_keys
