from __future__ import annotations

import argparse
import base64
import hashlib
from pathlib import Path
from typing import Any

from scripts.claude_git_mailbox_bridge import (
    CLAUDE_API_TO_GPT_PATH,
    GPT_TO_CLAUDE_PATH,
    MAILBOX_BRANCH,
    _MESSAGE_ID_RE,
    _content_api,
    _github_json,
    _headers,
    _token_from_env,
    fetch_fixed_file,
)


def request_id_from_gpt(text: str) -> str:
    first, headers = _headers(text)
    if first != "GPT_TO_CLAUDE" or headers.get("status", "").upper() != "REQUEST": return ""
    message_id = headers.get("message_id", "")
    return message_id if _MESSAGE_ID_RE.fullmatch(message_id) else ""


def reply_to_request_id(text: str) -> str:
    first, headers = _headers(text)
    if first != "CLAUDE_API_TO_GPT" or headers.get("identity", "").upper() != "STATELESS_API_RESPONDER": return ""
    message_id = headers.get("in_reply_to", "")
    return message_id if _MESSAGE_ID_RE.fullmatch(message_id) else ""


def normalize_gpt_request(text: str) -> tuple[str, str]:
    message_id = request_id_from_gpt(text)
    if not message_id: raise ValueError("invalid GPT_TO_CLAUDE REQUEST mailbox message")
    payload = str(text or "").strip()
    if len(payload) > 7400: payload = payload[:7400].rstrip() + "\n\n[GPT git mailbox message truncated by bounded bridge]"
    return message_id, (
        "AI_BUS\n" f"message_id: {message_id}\n" "from: GPT\n" "to: CLAUDE\n" "mode: DIRECT\n" "max_hops: 1\n\n"
        "This request is being answered by a stateless Anthropic API responder, not by the persistent/interactive Claude agent. "
        "The response must be labelled accordingly.\n\n" f"{payload}\n"
    )


def select_pending(repo: str, *, token: str) -> tuple[bool, str, str]:
    incoming, _ = fetch_fixed_file(repo, GPT_TO_CLAUDE_PATH, token=token)
    message_id = request_id_from_gpt(incoming)
    if not message_id: return False, "", ""
    _, envelope = normalize_gpt_request(incoming)
    try: outgoing, _ = fetch_fixed_file(repo, CLAUDE_API_TO_GPT_PATH, token=token)
    except RuntimeError as exc:
        if "HTTP 404" not in str(exc): raise
        outgoing = ""
    return reply_to_request_id(outgoing) != message_id, message_id, envelope


def _reply_message_id(request_id: str) -> str:
    return f"claude-api-reply-{hashlib.sha256(request_id.encode()).hexdigest()[:24]}"


def build_claude_mailbox_reply(request_id: str, bus_reply: str) -> str:
    if not _MESSAGE_ID_RE.fullmatch(str(request_id or "")): raise ValueError("invalid request id")
    text = str(bus_reply or "").strip(); first, headers = _headers(text)
    if first != "AI_BUS_REPLY" or headers.get("message_id") != request_id: raise ValueError("AI bus reply does not match GPT mailbox request")
    status = headers.get("status", "BLOCKED").upper()
    if status not in {"COMPLETED", "PARTIAL", "BLOCKED"}: status = "BLOCKED"
    return (
        "CLAUDE_API_TO_GPT\n" f"message_id: {_reply_message_id(request_id)}\n" "status: RESPONSE\n" f"in_reply_to: {request_id}\n"
        f"provider_status: {status}\n" "provider: CLAUDE\n" "identity: STATELESS_API_RESPONDER\n" "persistent_agent: false\n"
        "transport: AI_BUS_VIA_GIT_MAILBOX\n"
        "constraints: communication-only; no deploy; no trading/risk/capital/wallet/signing changes; no secrets\n\n"
        "[IDENTITY NOTICE] This response was generated by the stateless Claude/Anthropic API bridge. It is not a message authored by the persistent/interactive Claude agent.\n\n"
        f"{text}\n"
    )


def publish_reply(repo: str, *, token: str, request_id: str, bus_reply: str) -> None:
    content = build_claude_mailbox_reply(request_id, bus_reply); existing_sha = ""
    try: _, existing_sha = fetch_fixed_file(repo, CLAUDE_API_TO_GPT_PATH, token=token)
    except RuntimeError as exc:
        if "HTTP 404" not in str(exc): raise
    payload: dict[str, Any] = {"message": f"Claude API responder reply to GPT mailbox {request_id}", "content": base64.b64encode(content.encode()).decode(), "branch": MAILBOX_BRANCH}
    if existing_sha: payload["sha"] = existing_sha
    _github_json(_content_api(repo, CLAUDE_API_TO_GPT_PATH), token=token, method="PUT", payload=payload)


def main() -> int:
    parser = argparse.ArgumentParser(description="Bridge GPT mailbox requests to the stateless Claude API responder.")
    sub = parser.add_subparsers(dest="command", required=True)
    select = sub.add_parser("select-live"); select.add_argument("--repo", required=True); select.add_argument("--message-output", required=True)
    publish = sub.add_parser("publish-live"); publish.add_argument("--repo", required=True); publish.add_argument("--request-id", required=True); publish.add_argument("--reply-file", required=True)
    args = parser.parse_args(); token = _token_from_env()
    if args.command == "select-live":
        pending, message_id, envelope = select_pending(args.repo, token=token)
        if pending: Path(args.message_output).write_text(envelope, encoding="utf-8")
        print(f"pending={'true' if pending else 'false'}"); print(f"message_id={message_id}"); return 0
    publish_reply(args.repo, token=token, request_id=args.request_id, bus_reply=Path(args.reply_file).read_text(encoding="utf-8", errors="replace")); return 0


if __name__ == "__main__": raise SystemExit(main())
